name: Rollback Production

on:
  workflow_dispatch:

jobs:
  rollback-production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Rollback to previous version
        run: |
          echo "🔄 Starting rollback process..."
          
          # Obtener nombres dinámicos del stack de CloudFormation
          STACK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name calculadora-prod-stack --query "Stacks[0].Outputs" --region us-east-1 --output json)
          
          CLUSTER_NAME=$(echo $STACK_OUTPUTS | jq -r '.[] | select(.OutputKey=="ECSClusterName") | .OutputValue')
          SERVICE_NAME=$(echo $STACK_OUTPUTS | jq -r '.[] | select(.OutputKey=="ECSServiceName") | .OutputValue')
          
          echo "Cluster: $CLUSTER_NAME"
          echo "Service: $SERVICE_NAME"
          
          # Obtener la imagen de rollback
          ROLLBACK_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:rollback"
          echo "Using rollback image: $ROLLBACK_IMAGE"
          
          # CORREGIR: Buscar task definition existente con rollback image
          TASK_DEFS=$(aws ecs list-task-definitions --family-prefix calculadora-production-task --sort DESC --max-items 10 --query "taskDefinitionArns[]" --output text)
          
          EXISTING_ROLLBACK_TASK=""
          for task_def_arn in $TASK_DEFS; do
            IMAGE=$(aws ecs describe-task-definition --task-definition "$task_def_arn" --query 'taskDefinition.containerDefinitions[0].image' --output text)
            echo "Checking task definition: $task_def_arn with image: $IMAGE"
            if [[ "$IMAGE" == "$ROLLBACK_IMAGE" ]]; then
              EXISTING_ROLLBACK_TASK="$task_def_arn"
              echo "✅ Found existing rollback task definition: $EXISTING_ROLLBACK_TASK"
              break
            fi
          done
          
          if [ -n "$EXISTING_ROLLBACK_TASK" ]; then
            echo "📋 Reusing existing rollback task definition: $EXISTING_ROLLBACK_TASK"
            ROLLBACK_TASK_DEF="$EXISTING_ROLLBACK_TASK"
          else
            echo "📝 Creating new rollback task definition..."
            # Solo crear nueva si no existe una con rollback
            TASK_DEF=$(aws ecs describe-task-definition --task-definition calculadora-production-task --query 'taskDefinition' --output json)
            NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$ROLLBACK_IMAGE" '.containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')
            ROLLBACK_TASK_DEF=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)
          fi
          
          echo "🚀 Updating service to use rollback task definition: $ROLLBACK_TASK_DEF"
          aws ecs update-service --cluster $CLUSTER_NAME \
                                --service $SERVICE_NAME \
                                --task-definition $ROLLBACK_TASK_DEF \
                                --force-new-deployment
          
          # Esperar estabilidad
          echo "⏳ Waiting for service to stabilize..."
          aws ecs wait services-stable --cluster $CLUSTER_NAME --services $SERVICE_NAME

      - name: Verify rollback
        run: |
          echo "Rollback completed successfully!"
          echo "Service should now be running the previous version."
          
          # Obtener nombres dinámicos nuevamente
          STACK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name calculadora-prod-stack --query "Stacks[0].Outputs" --region us-east-1 --output json)
          CLUSTER_NAME=$(echo $STACK_OUTPUTS | jq -r '.[] | select(.OutputKey=="ECSClusterName") | .OutputValue')
          SERVICE_NAME=$(echo $STACK_OUTPUTS | jq -r '.[] | select(.OutputKey=="ECSServiceName") | .OutputValue')
          
          # Verificar que el servicio esté corriendo
          SERVICE_STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].status' --output text)
          echo "Service status: $SERVICE_STATUS"
          
          # Mostrar cuántas tareas están corriendo
          RUNNING_COUNT=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].runningCount' --output text)
          DESIRED_COUNT=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].desiredCount' --output text)
          echo "Tasks running: $RUNNING_COUNT/$DESIRED_COUNT"